// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NationalParks.Models;

namespace NationalParks.Migrations
{
    [DbContext(typeof(NationalParksContext))]
    [Migration("20200821183635_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("NationalParks.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.Property<string>("StateOrNational");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Name = "Yosemite National Park",
                            State = "California",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 2,
                            Name = "Glacier National Park",
                            State = "Montana",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 3,
                            Name = "Zion National Park",
                            State = "Utah",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 4,
                            Name = "Olympic National Park",
                            State = "Washington",
                            StateOrNational = "National"
                        },
                        new
                        {
                            ParkId = 5,
                            Name = "Ecola State Park",
                            State = "Oregon",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 6,
                            Name = "Niagara Falls State Park",
                            State = "New York",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 7,
                            Name = "Smith Rock State Park",
                            State = "Oregon",
                            StateOrNational = "State"
                        },
                        new
                        {
                            ParkId = 8,
                            Name = "Shasta State Historic Park",
                            State = "California",
                            StateOrNational = "State"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
